<h1> SPEECH TO TEXT

In [ ]:
! pip install -q transformers

In [ ]:
import librosa
import torch
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer

In [ ]:
#load pre-trained model and tokenizer
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.10/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:733: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of the model checkpoint at facebook/wav2vec2-base-960h were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_g', 'wav2vec2.encoder.pos_conv_embed.conv.weight_v']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You sho

In [ ]:
#load any audio file of your choice
speech, rate = librosa.load("/content/Test.mp3",sr=16000)

In [ ]:
import IPython.display as display
display.Audio("/content/Test.mp3", autoplay=True)

In [ ]:
input_values = tokenizer(speech, return_tensors = 'pt').input_values

In [ ]:
input_values

tensor([[0.0032, 0.0032, 0.0032,  ..., 0.0032, 0.0032, 0.0032]])

In [ ]:
#Store logits (non-normalized predictions)
logits = model(input_values).logits

In [ ]:
logits

tensor([[[ 14.7486, -25.7812, -25.4406,  ...,  -6.2802,  -7.6492,  -7.9503],
         [ 14.2134, -25.4631, -25.1266,  ...,  -6.2478,  -7.3839,  -8.0082],
         [ 14.0006, -26.0518, -25.7212,  ...,  -6.6468,  -7.9237,  -8.2037],
         ...,
         [ 13.9291, -24.1978, -23.8496,  ...,  -4.3936,  -7.4470,  -7.1892],
         [ 13.9290, -24.1965, -23.8485,  ...,  -4.3928,  -7.4459,  -7.1889],
         [ 14.5193, -25.8105, -25.4926,  ...,  -6.2229,  -7.7970,  -7.7154]]],
       grad_fn=<ViewBackward0>)

In [ ]:
#Store predicted id's
predicted_ids = torch.argmax(logits, dim =-1)
predicted_ids

tensor([[ 0,  0,  0,  0,  0, 11, 11,  0,  0,  0,  0, 10, 21,  0, 11,  4,  4, 11,
         11,  0,  0,  5, 15,  0,  0, 15,  0,  0,  0,  8,  0,  0,  0,  4,  4,  0,
         21,  8,  8,  0,  0,  8, 14,  0,  4,  4,  0, 17,  0,  0,  0,  8,  0, 13,
          0,  0,  9,  0,  0,  0, 10,  9, 21, 21,  4,  4,  4,  4,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0]])

In [ ]:
#decode the audio to generate text
transcriptions = tokenizer.decode(predicted_ids[0])


In [ ]:
print(transcriptions)

HIGH HELLO GOOD MORNING


<H1> TEXT TO SPEECH

In [ ]:
!pip install gtts

In [ ]:
from gtts import gTTS

In [ ]:
language = "en"

In [ ]:
text = "HI HELLO GOOD MORNING"

In [ ]:
speech = gTTS(text=text,lang=language, slow = False)

In [ ]:
speech.save("Test.mp3")